### ISSUE TITLE
跳转界面下面是空白

### ISSUE THREAD

**Issue by starssr** [wenjing-xin/plugins-links-security-detect#1]
![image](https://github.com/wenjing-xin/plugins-links-security-detect/assets/72611505/64f5a2a9-cfc9-4302-beda-51ddad121112)
链接是
https://starssr.com/jumpGo?goUrl=https%3A%2F%2Fgravatar.loli.net%2Favatar%2F255176ca08cba377474d9fb4c5637354%3Fs%3D100

**Comment by starssr** [comment]
更新之前是好的

**Comment by wenjing-xin** [comment]
> https://starssr.com/jumpGo?goUrl=https%3A%2F%2Fgravatar.loli.net%2Favatar%2F255176ca08cba377474d9fb4c5637354%3Fs%3D100

![image](https://github.com/wenjing-xin/plugins-links-security-detect/assets/130843859/713f2d1d-873c-40a2-9d6c-62986d693d60)
我刚刚测试了下 没问题呀。你重启插件试试

**Comment by wenjing-xin** [comment]
> 更新之前是好的

如果授权了，请加下售后群
